services:
  - type: web
    name: craftproof-backend
    runtime: python
    region: oregon # or frankfurt, ohio, singapore
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: craftproof-frontend
    runtime: static
    region: oregon
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: craftproof-backend
          property: url
